apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mongodb-backup
  annotations:
    github.com/project-slug: Madurad/mongodb-backup
spec:
  type: other
  lifecycle: unknown
  owner: guests
